M48
; DRILL file {KiCad (7.0.0)} date Fri Aug 25 13:07:58 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-08-25T13:07:58+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0118
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0315
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0551
%
G90
G05
T1
X1.9Y-2.5
X1.9Y-2.7
X2.3Y-2.0
X2.3Y-2.5
X2.3Y-2.7
X3.1Y-2.7
T2
X1.7Y-1.8
X2.2Y-1.8
X2.5Y-1.8
X3.0Y-1.8
T3
X2.4Y-2.4409
X2.9Y-2.4409
T0
M30
